data "aws_ami" "ubuntu" {
  most_recent = true
  owners      = ["099720109477"]

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

resource "aws_instance" "transaction_processor" {
  ami                    = data.aws_ami.ubuntu.id
  instance_type          = "t3.micro"
  subnet_id              = aws_subnet.public.id
  vpc_security_group_ids = [aws_security_group.processing.id]

  tags = {
    Name      = "transaction-processing-generated"
    ManagedBy = "Terraform"
    Project   = "AWS Automated Transaction Processing"
  }
}

output "generated_ec2_instance_id" {
  description = "ID of the EC2 instance generated by Terraform"
  value       = aws_instance.transaction_processor.id
}

output "generated_ec2_public_ip" {
  description = "Public IP of the generated EC2 instance"
  value       = aws_instance.transaction_processor.public_ip
}
