name: Terraform Infrastructure Deployment
 
on:
  push:
    branches:
      - feature/ecs-processing
  workflow_dispatch:
 
permissions:
  id-token: write
  contents: read
 
jobs:
  terraform:
    name: Deploy AWS Infrastructure
    runs-on: ubuntu-latest
 
    defaults:
      run:
        working-directory: terraform
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::265145884274:role/github-terraform-deployment-role
          aws-region: us-east-1
 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
 
      - name: Terraform Init
        run: terraform init
 
      - name: Terraform Format Check
        run: terraform fmt -check
 
      - name: Terraform Validate
        run: terraform validate
 
      - name: Terraform Plan
        run: terraform plan -out=tfplan
 
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

tfplan
